### ISSUE TITLE
I am not able to get anything from code

### ISSUE THREAD

**Issue by tahir80** [JBramauer/pepperspeechrecognition#1]
Hi, I just run this code om my pepper and it says this:
[I] 1532440945.653757 3600 qimessaging.session: Session listener created on tcp://0.0.0.0:0
[W] 1532440945.654501 3604 qi.path.sdklayout: No Application was created, trying to deduce paths
[I] 1532440945.654548 3600 qimessaging.transportserver: TransportServer will listen on: tcp://127.0.0.1:59990
[I] 1532440945.654629 3600 qimessaging.transportserver: TransportServer will listen on: tcp://198.18.0.1:59990
[I] 1532440945.654682 3600 qimessaging.transportserver: TransportServer will listen on: tcp://192.168.1.87:59990
[W] 1532440945.667895 3600 qitype.metaobject: Method(114) already defined (and overriden): BIND_PYTHON::(m)
[W] 1532440945.668511 3600 qitype.metaobject: Method(115) already defined (and overriden): addParam::(m)
[W] 1532440945.668891 3600 qitype.metaobject: Method(116) already defined (and overriden): autoBind::(m)
[W] 1532440945.669300 3600 qitype.metaobject: Method(117) already defined (and overriden): calcRMSLevel::(m)
[W] 1532440945.669513 3600 qitype.metaobject: Method(117) already defined (and overriden): calcRMSLevel::(m)
[W] 1532440945.670040 3600 qitype.metaobject: Method(119) already defined (and overriden): convertStr2SignedInt::(m)
[W] 1532440945.670259 3600 qitype.metaobject: Method(119) already defined (and overriden): convertStr2SignedInt::(m)
[W] 1532440945.670469 3600 qitype.metaobject: Method(119) already defined (and overriden): convertStr2SignedInt::(m)
[W] 1532440945.670679 3600 qitype.metaobject: Method(119) already defined (and overriden): convertStr2SignedInt::(m)
[W] 1532440945.670905 3600 qitype.metaobject: Method(119) already defined (and overriden): convertStr2SignedInt::(m)
[W] 1532440945.671375 3600 qitype.metaobject: Method(100) already defined (and overriden): exit::()
[W] 1532440945.671717 3600 qitype.metaobject: Method(122) already defined (and overriden): functionName::(m)
[W] 1532440945.672078 3600 qitype.metaobject: Method(112) already defined (and overriden): getBrokerName::()
[W] 1532440945.672456 3600 qitype.metaobject: Method(124) already defined (and overriden): getModule::(m)
[W] 1532440945.673060 3600 qitype.metaobject: Method(127) already defined (and overriden): pause::()
[W] 1532440945.673447 3600 qitype.metaobject: Method(128) already defined (and overriden): processRemote::(mmmm)
[W] 1532440945.673673 3600 qitype.metaobject: Method(128) already defined (and overriden): processRemote::(mmmm)
[W] 1532440945.674025 3600 qitype.metaobject: Method(128) already defined (and overriden): processRemote::(mmmm)
[W] 1532440945.674265 3600 qitype.metaobject: Method(128) already defined (and overriden): processRemote::(mmmm)
[W] 1532440945.674493 3600 qitype.metaobject: Method(128) already defined (and overriden): processRemote::(mmmm)
[W] 1532440945.674728 3600 qitype.metaobject: Method(128) already defined (and overriden): processRemote::(mmmm)
[W] 1532440945.674980 3600 qitype.metaobject: Method(128) already defined (and overriden): processRemote::(mmmm)
[W] 1532440945.675199 3600 qitype.metaobject: Method(128) already defined (and overriden): processRemote::(mmmm)
[W] 1532440945.675429 3600 qitype.metaobject: Method(128) already defined (and overriden): processRemote::(mmmm)
[W] 1532440945.675649 3600 qitype.metaobject: Method(128) already defined (and overriden): processRemote::(mmmm)
[W] 1532440945.675887 3600 qitype.metaobject: Method(128) already defined (and overriden): processRemote::(mmmm)
[W] 1532440945.676109 3600 qitype.metaobject: Method(128) already defined (and overriden): processRemote::(mmmm)
[W] 1532440945.676332 3600 qitype.metaobject: Method(128) already defined (and overriden): processRemote::(mmmm)
[W] 1532440945.676554 3600 qitype.metaobject: Method(128) already defined (and overriden): processRemote::(mmmm)
[W] 1532440945.677045 3600 qitype.metaobject: Method(129) already defined (and overriden): pythonChanged::(mmm)
[W] 1532440945.677266 3600 qitype.metaobject: Method(129) already defined (and overriden): pythonChanged::(mmm)
[W] 1532440945.677481 3600 qitype.metaobject: Method(129) already defined (and overriden): pythonChanged::(mmm)
[W] 1532440945.677848 3600 qitype.metaobject: Method(130) already defined (and overriden): recognize::(m)
[W] 1532440945.678051 3600 qitype.metaobject: Method(130) already defined (and overriden): recognize::(m)
[W] 1532440945.678267 3600 qitype.metaobject: Method(130) already defined (and overriden): recognize::(m)
[W] 1532440945.678482 3600 qitype.metaobject: Method(130) already defined (and overriden): recognize::(m)
[W] 1532440945.678695 3600 qitype.metaobject: Method(130) already defined (and overriden): recognize::(m)
[W] 1532440945.678925 3600 qitype.metaobject: Method(130) already defined (and overriden): recognize::(m)
[W] 1532440945.679129 3600 qitype.metaobject: Method(130) already defined (and overriden): recognize::(m)
[W] 1532440945.679603 3600 qitype.metaobject: Method(132) already defined (and overriden): setAutoDetectionThreshold::(m)
[W] 1532440945.679975 3600 qitype.metaobject: Method(133) already defined (and overriden): setHoldTime::(m)
[W] 1532440945.680323 3600 qitype.metaobject: Method(134) already defined (and overriden): setIdleReleaseTime::(m)
[W] 1532440945.680662 3600 qitype.metaobject: Method(135) already defined (and overriden): setLanguage::(m)
[W] 1532440945.681019 3600 qitype.metaobject: Method(136) already defined (and overriden): setLookaheadDuration::(m)
[W] 1532440945.681361 3600 qitype.metaobject: Method(137) already defined (and overriden): setMaxRecordingDuration::(m)
[W] 1532440945.681703 3600 qitype.metaobject: Method(138) already defined (and overriden): setModuleDescription::(m)
[W] 1532440945.682077 3600 qitype.metaobject: Method(139) already defined (and overriden): start::()
[W] 1532440945.682285 3600 qitype.metaobject: Method(139) already defined (and overriden): start::()
[W] 1532440945.682493 3600 qitype.metaobject: Method(139) already defined (and overriden): start::()
[W] 1532440945.683211 3600 qitype.metaobject: Method(143) already defined (and overriden): stopRecordingAndRecognize::()
[W] 1532440945.683412 3600 qitype.metaobject: Method(143) already defined (and overriden): stopRecordingAndRecognize::()
[W] 1532440945.683609 3600 qitype.metaobject: Method(143) already defined (and overriden): stopRecordingAndRecognize::()
[W] 1532440945.683823 3600 qitype.metaobject: Method(143) already defined (and overriden): stopRecordingAndRecognize::()
[W] 1532440945.684078 3600 qitype.metaobject: Method(143) already defined (and overriden): stopRecordingAndRecognize::()
[W] 1532440945.684313 3600 qitype.metaobject: Method(103) already defined (and overriden): version::()

How can I configure this?

**Comment by tahir80** [comment]
the issue has been resolved!, I forgot to un-comment lines

**Comment by dbasbabasi** [comment]
Hi I have the same problem. How did you solve it ?

**Comment by tahir80** [comment]
do not forget to un-comment few lines at the end of
module_speechrecognition.py
-----------------------------------
SpeechRecognition.start()
SpeechRecognition.startRecording()
SpeechRecognition.calibrate()
SpeechRecognition.enableAutoDetection()
SpeechRecognition.startRecording()

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
07/26/18,
11:33:49 AM

*Regards,*
******************************************

*Tahir Abbas*
*Lecturer, Software Engg. Dept.*
*MUST University, Mirpur, AJK.*
*Pakistan. +92.331.7603300*
********************************************
